version: "3.9"
services:
  app:
    image: graalvm-builder-app:static-1
    build:
      dockerfile: Dockerfile
      args:
        - REPO_ADDRESS=https://github.com/benayat/spring-boot-stomp-native
        - REPO_NAME=spring-boot-stomp-native
        - ARTIFACT_ID=spring-websocket-demo
    volumes:
      - m2:/root/.m2
volumes:
  m2:
    driver: local
  target:
    driver: local